codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "**/__pycache__"
  - "*.pyc"
  - "setup.py"
  - "venv/"
  - ".venv/"
  - "Client"
  - "htmlcov"
  - "web"
  - "build"
  - "dist"
  - "src/hardware/"
