[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | node_modules
  | \.git
  | __pycache__
  | migrations
  | Client
  | htmlcov
  | web
  | build
  | dist
)/
'''