name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

#    - name: Set up Node.js
#      uses: actions/setup-node@v4
#      with:
#        node-version: 18
#        cache: 'npm'

    - name: Install Python dependencies
      run: |
        pip install bandit mypy pip-audit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#    - name: Install Node.js dependencies
#      run: npm ci

    - name: Python security check
      run: |
        # To uncomment the following lines, ensure you have a .bandit file configured
        bandit -r . -f sarif -o bandit.sarif || true
        pip-audit --format=sarif --output=pip-audit.sarif

    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: |
          bandit.sarif
          pip-audit.sarif

    - name: Python type checking
      run: mypy .

#    - name: JavaScript/TypeScript linting
#      run: |
#        npm run lint || true
#        npm audit || true
