name: Code Quality
# Bandit ->  Finds common security issues in Python code, such as:
#              - insecure imports,
#              - hardcoded passwords,
#              - unsafe function usage
# CodeQL  ->  Performs deep semantic analysis to identify potential vulnerabilities in codebases
# next?
# - pip-audit -> Checks Python environments and dependency files for known vulnerabilities
# - mypy -> Static type checking for Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for codeql-action & bandit to upload SARIF results
      actions: read # only required for a private repository, for codeql-action (upload) to get the Action run status
      packages: read # required to fetch internal or private CodeQL packs
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: python
          build-mode: none
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install Python dependencies
      run: |
        pip install bandit pip-audit numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Python security check (Bandit)
      uses: shundor/python-bandit-scan@ab1d87dfccc5a0ffab88be3aaac6ffe35c10d6cd
      with:
        exit_zero: true # exit with 0, even with results found
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information.
        path: src/  # comma-separated list of paths (files or directories)
        # level: Report only issues of a given severity level or higher. LOW, MEDIUM, HIGH or UNDEFINED (default)
        # confidence: Report only issues of a given confidence level or higher. LOW, MEDIUM, HIGH or UNDEFINED (default)
        excluded_paths: web/ # comma-separated list of paths (glob patterns supported)
        # skips: comma-separated list of test IDs to skip
        # ini_path: .bandit file that supplies command line arguments

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - if: matrix.build-mode == 'manual'
      shell: bash
      run: |
        echo 'If you are using a "manual" build mode for one or more of the' \
          'languages you are analyzing, replace this with the commands to build' \
          'your code, for example:'
        echo '  make bootstrap'
        echo '  make release'
        exit 1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

    - name: Scan for vulnerabilities with pip-audit
      uses: pypa/gh-action-pip-audit@v1.1.0
      with:
        inputs: |
          -r requirements.txt
        no-deps: true
        # Enable SARIF upload to the Security tab
        sarif: true
      continue-on-error: true

#    - name: Python type checking
#      run: mypy .

#    - name: JavaScript/TypeScript linting
#      run: |
#        npm run lint || true
#        npm audit || true
